
## If you have created a new hugo site and dont know how to do next, just DELETE config.toml file at its root directory and get the copy the example config file in exampleSite folder.

## Your posts files should be in /content/posts/ folder. See the [params.mainSections] section below.

params:

    dateFormat: "Jan 2, 2006"

    footerCopyright: 
        siteUrl: Your Domain / Name  ## This would show after footer text "© 202X"

    logo: "/favicon.png"  ## at /static folder
    
    mainSections: posts  ## This means that you need to put posts .md files in the folder /content/posts/ , then these files can be viewed at Homepage.

    ## Buttons Text
    PageBack: "Back to Prev"
    OlderPosts: "Older Page"
    NewerPosts: "Newer Page"
    read_more: "Read More"

    ## for websites hosted on mainland China servers. Just DELETE this whole part if no need
    ## 下面这部分是页脚的备案信息。如果不需要，直接删掉或用 # 注释掉该部分即可
    ##ICP: 
        ##province: 京
        ##certnum: "06010200"
